[package]
name = "indi-rust"
version = "1.0.0"
edition = "2021"

[dependencies]
oracle = {version = "0.5", features = ["chrono"]}
chrono = "0.4.19"
remotefs = "0.2.0"
remotefs-ssh = "0.1.0"
regex = "1"
linecount = "0.1.0"