FROM rust:1.59-alpine3.15 AS build
WORKDIR /app
COPY . .
ENV RUSTFLAGS="-C target-feature=-crt-static"
RUN apk add libc-dev openssl-dev && apk update
RUN cargo build --release

# FROM alpine:3.15
# FROM asg1612/alpine-oracle-instantclient
FROM oracle-base
ARG APP_NAME
### environment variables - start
ARG ARG_DB_INDI_USERNAME
ARG ARG_DB_INDI_PASSWORD
ARG ARG_DB_INDI_URL
ENV DB_INDI_USERNAME=$ARG_DB_INDI_USERNAME
ENV DB_INDI_PASSWORD=$ARG_DB_INDI_PASSWORD
ENV DB_INDI_URL=$ARG_DB_INDI_URL
ARG ARG_DB_OBT_USERNAME
ARG ARG_DB_OBT_PASSWORD
ARG ARG_DB_OBT_URL
ENV DB_OBT_USERNAME=$ARG_DB_OBT_USERNAME
ENV DB_OBT_PASSWORD=$ARG_DB_OBT_PASSWORD
ENV DB_OBT_URL=$ARG_DB_OBT_URL
ARG ARG_SOURCE_SFTP_HOST
ARG ARG_SOURCE_SFTP_USERNAME
ARG ARG_SOURCE_SFTP_PASSWORD
ARG ARG_SOURCE_SFTP_PATH
ARG ARG_SOURCE_FILE
ENV SOURCE_SFTP_HOST=$ARG_SOURCE_SFTP_HOST
ENV SOURCE_SFTP_USERNAME=$ARG_SOURCE_SFTP_USERNAME
ENV SOURCE_SFTP_PASSWORD=$ARG_SOURCE_SFTP_PASSWORD
ENV SOURCE_SFTP_PATH=$ARG_SOURCE_SFTP_PATH
ENV SOURCE_FILE=$ARG_SOURCE_FILE
ARG ARG_LEGACY_SFTP_HOST
ARG ARG_LEGACY_SFTP_USERNAME
ARG ARG_LEGACY_SFTP_PASSWORD
ARG ARG_LEGACY_SFTP_PATH
ARG ARG_LEGACY_FILE
ENV LEGACY_SFTP_HOST=$ARG_LEGACY_SFTP_HOST
ENV LEGACY_SFTP_USERNAME=$ARG_LEGACY_SFTP_USERNAME
ENV LEGACY_SFTP_PASSWORD=$ARG_LEGACY_SFTP_PASSWORD
ENV LEGACY_SFTP_PATH=$ARG_LEGACY_SFTP_PATH
### environment variables - end
WORKDIR /app
COPY --from=build /app/target/release/$APP_NAME ./application
RUN apk add --update libgcc && apk add openssl&& rm -rf /var/cache/apk/*
RUN chmod +x application
ENTRYPOINT ["./application"]